ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = system;

CREATE USER sgf_admin IDENTIFIED BY Admin123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, DBA TO sgf_admin;

-- Không viết gì thêm ở file này
