ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = sgf_admin;

-- Code ở phía sau 2 dòng lệnh trên

-- =============================================
-- 1. CUSTOMER TYPE TABLE
-- =============================================
CREATE TABLE CUSTOMERTYPE (
    CustomerTypeID   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CustomerTypeName NVARCHAR2(40) NOT NULL CHECK(CustomerTypeName IN ('Bronze', 'Silver', 'Gold', 'VIP')),
    Discount         NUMBER(5,2) NOT NULL,
    Detail           NVARCHAR2(200) NOT NULL,
    SpendingLimit    NUMBER DEFAULT 0 NOT NULL
);

-- =============================================
-- 2. CUSTOMER TABLE
-- =============================================
CREATE TABLE CUSTOMER (
    CustomerID            NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CustomerTypeID        NUMBER,
    FirstName             NVARCHAR2(40) NOT NULL,
    LastName              NVARCHAR2(20) NOT NULL,
    CompanyName           NVARCHAR2(40),
    Phone                 VARCHAR2(15) NOT NULL UNIQUE,
    Address               NVARCHAR2(255),
    Email                 VARCHAR2(100) UNIQUE,
    CreatedDate           DATE DEFAULT SYSDATE NOT NULL,
    TotalAccumulatedSpent NUMBER(19,4) DEFAULT 0 CHECK (TotalAccumulatedSpent >= 0),
    CONSTRAINT fk_customer_customertype FOREIGN KEY (CustomerTypeID) REFERENCES CUSTOMERTYPE(CustomerTypeID)
);

-- =============================================
-- 3. CATEGORY TABLE
-- =============================================
CREATE TABLE CATEGORY (
    CategoryID   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CategoryName NVARCHAR2(30) NOT NULL
);

-- =============================================
-- 4. PRODUCT TABLE
-- =============================================
CREATE TABLE PRODUCT (
    ProductID     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    ProductName   NVARCHAR2(100) NOT NULL,
    Detail        NVARCHAR2(200),
    ProductPrice  NUMBER CHECK (ProductPrice > 0),
    ProductStatus NUMBER CHECK (ProductStatus IN (0,1)),
    CategoryID    NUMBER,
    AllowReturn   NUMBER(1) NOT NULL CHECK (AllowReturn IN (0,1)),
    ImageURL      VARCHAR2(4000),
    CONSTRAINT fk_product_category FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

-- =============================================
-- 5. PRODUCTTYPE TABLE
-- =============================================
CREATE TABLE PRODUCTTYPE (
    ProductTypeID   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    ProductTypeName VARCHAR2(30) NOT NULL,
    CategoryID      NUMBER NOT NULL
);

-- =============================================
-- 6. COMBO TABLE
-- =============================================
CREATE TABLE COMBO (
    ComboID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    ComboPrice NUMBER(19,4) NOT NULL
);

-- =============================================
-- 7. COMBODETAIL TABLE
-- =============================================
CREATE TABLE COMBODETAIL (
    ComboID   NUMBER,
    ProductID NUMBER,
    Quantity  NUMBER CHECK (Quantity > 0),
    PRIMARY KEY (ComboID, ProductID),
    CONSTRAINT fk_cd_combo FOREIGN KEY (ComboID) REFERENCES COMBO(ComboID),
    CONSTRAINT fk_cd_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 8. WAREHOUSE TABLE
-- =============================================
CREATE TABLE WAREHOUSE (
    WareHouseID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    WareHouseName  NVARCHAR2(40) NOT NULL,
    ManagerID      NUMBER NOT NULL,
    Address        NVARCHAR2(50) NOT NULL,
    ContactNumber  VARCHAR2(15) NOT NULL,
    Capacity       NUMBER NOT NULL,
    Status         NUMBER CHECK (Status IN (0,1)),
    WarehouseType  NUMBER CHECK (WarehouseType IN (1,2,3))
);

-- =============================================
-- 9. EMPLOYEE TABLE
-- =============================================
CREATE TABLE EMPLOYEE (
    EmployeeID   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    Fullname     NVARCHAR2(100) NOT NULL,
    Email        VARCHAR2(100) UNIQUE,
    Phone        VARCHAR2(15) NOT NULL CHECK (LENGTH(Phone) >= 10),
    PasswordHash VARCHAR2(255) NOT NULL,
    Status       NUMBER(1) DEFAULT 1 CHECK (Status IN (0,1))
);

-- Add the FK for warehouse manager now that EMPLOYEE exists
ALTER TABLE WAREHOUSE ADD CONSTRAINT fk_warehouse_employee FOREIGN KEY (ManagerID) REFERENCES EMPLOYEE(EmployeeID);

-- =============================================
-- 10. ROLE TABLE
-- =============================================
CREATE TABLE ROLE (
    RoleID   NUMBER PRIMARY KEY CHECK (RoleID IN (0,1,2)),
    RoleName VARCHAR2(100) NOT NULL
);

-- =============================================
-- 11. EMPLOYEEROLE TABLE
-- =============================================
CREATE TABLE EMPLOYEEROLE (
    EmployeeID NUMBER,
    RoleID     NUMBER,
    PRIMARY KEY (EmployeeID, RoleID),
    CONSTRAINT fk_er_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT fk_er_role FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);

-- =============================================
-- 12. SHIPCOMPANY TABLE
-- =============================================
CREATE TABLE SHIPCOMPANY (
    ShipCompanyID   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    ShipCompanyName NVARCHAR2(100) NOT NULL UNIQUE,
    SupportedRegion VARCHAR2(50) NOT NULL,
    Phone           VARCHAR2(15) NOT NULL,
    Email           VARCHAR2(100),
    Address         NVARCHAR2(255),
    Notes           NVARCHAR2(500),
    Status          NUMBER(1) DEFAULT 1 CHECK (Status IN (0,1))
);

-- =============================================
-- 13. INVOICE TABLE (references Employee, Customer)
-- =============================================
CREATE TABLE INVOICE (
    InvoiceID       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CustomerID      NUMBER NOT NULL,
    EmployeeID      NUMBER,
    SaleChannelCode NUMBER NOT NULL,
    TotalAmount     NUMBER(19,4) CHECK (TotalAmount >= 0),
    TaxAmount       NUMBER(19,4) DEFAULT 0,
    FinalAmount     NUMBER(19,4) CHECK (FinalAmount >= 0),
    Status          VARCHAR2(20) NOT NULL,
    InvoiceDate     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_invoice_customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
    CONSTRAINT fk_invoice_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);

-- =============================================
-- 14. ORDER TABLE (references Customer, Employee, Invoice, ShipCompany)
-- =============================================
CREATE TABLE "ORDER" (
    OrderID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CustomerID     NUMBER NOT NULL,
    EmployeeID     NUMBER NOT NULL,
    InvoiceID      NUMBER,
    ShipCode       VARCHAR2(20),
    ShipCompanyID  NUMBER,
    TotalAmount    NUMBER(19,4) CHECK (TotalAmount >= 0),
    OrderStatus    NUMBER NOT NULL CHECK (OrderStatus IN (0,1,2,3,4,5)),
    ShippingStatus NUMBER CHECK (ShippingStatus IN (0,1,2,3)),
    ShipmentNote   VARCHAR2(100),
    ShippingFee    NUMBER CHECK (ShippingFee >= 0),
    ExportTicketID NUMBER,
    CONSTRAINT fk_order_customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
    CONSTRAINT fk_order_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT fk_order_invoice FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID),
    CONSTRAINT fk_order_shipcompany FOREIGN KEY (ShipCompanyID) REFERENCES SHIPCOMPANY(ShipCompanyID)
);

-- =============================================
-- 15. ORDERDETAIL TABLE (references Order, Product, Combo)
-- =============================================
CREATE TABLE ORDERDETAIL (
    OrderDetailID  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    OrderID        NUMBER NOT NULL,
    ProductID      NUMBER NOT NULL,
    ComboID        NUMBER,
    Quantity       NUMBER CHECK (Quantity > 0),
    UnitPrice      NUMBER(19,4) CHECK (UnitPrice >= 0),
    DiscountAmount NUMBER(19,4) DEFAULT 0,
    TotalAmount    NUMBER(19,4) NOT NULL,
    CONSTRAINT fk_od_order FOREIGN KEY (OrderID) REFERENCES "ORDER"(OrderID),
    CONSTRAINT fk_od_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    CONSTRAINT fk_od_combo FOREIGN KEY (ComboID) REFERENCES COMBO(ComboID)
);

-- =============================================
-- 16. INVOICEDETAIL TABLE (references Invoice, Product, Combo)
-- =============================================
CREATE TABLE INVOICEDETAIL (
    InvoiceDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    InvoiceID       NUMBER NOT NULL,
    ProductID       NUMBER NOT NULL,
    ComboID         NUMBER,
    Quantity        NUMBER CHECK (Quantity > 0),
    UnitPrice       NUMBER(19,4) CHECK (UnitPrice >= 0),
    DiscountAmount  NUMBER(19,4) DEFAULT 0,
    TotalAmount     NUMBER(19,4) NOT NULL,
    CONSTRAINT fk_id_invoice FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID),
    CONSTRAINT fk_id_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    CONSTRAINT fk_id_combo FOREIGN KEY (ComboID) REFERENCES COMBO(ComboID)
);

-- =============================================
-- 17. PAYMENTMETHOD TABLE
-- =============================================
CREATE TABLE PAYMENTMETHOD (
    PaymentMethodID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    PaymentName     NVARCHAR2(100) NOT NULL UNIQUE,
    Status          NUMBER(1) CHECK (Status IN (0,1))
);

-- =============================================
-- 18. PAYMENT TABLE (references Invoice, PaymentMethod)
-- =============================================
CREATE TABLE PAYMENT (
    PaymentID       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    InvoiceID       NUMBER NOT NULL,
    PaymentMethodID NUMBER NOT NULL,
    AmountPaid      NUMBER(19,4) CHECK (AmountPaid > 0),
    ReferenceCode   VARCHAR2(100),
    PaymentDate     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_invoice FOREIGN KEY (InvoiceID) REFERENCES INVOICE(InvoiceID),
    CONSTRAINT fk_payment_pm FOREIGN KEY (PaymentMethodID) REFERENCES PAYMENTMETHOD(PaymentMethodID)
);

-- =============================================
-- 19. RETURNPOLICY TABLE
-- =============================================
CREATE TABLE RETURNPOLICY (
    PolicyID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    PolicyName      NVARCHAR2(100) NOT NULL,
    MaxReturnDays   NUMBER CHECK (MaxReturnDays >= 0),
    PenaltyFeeRate  DECIMAL(5,2) CHECK (PenaltyFeeRate >= 0 AND PenaltyFeeRate <= 100),
    EffectiveDate   DATE NOT NULL,
    IsActive        NUMBER CHECK (IsActive IN (0,1))
);

-- =============================================
-- 20. ORDERRETURN TABLE (references Order, Employee)
-- =============================================
CREATE TABLE ORDERRETURN (
    ReturnID      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    OrderID       NUMBER NOT NULL,
    EmployeeID    NUMBER NOT NULL,
    ReturnDate    DATE DEFAULT SYSDATE,
    Reason        NVARCHAR2(255),
    TotalRefund   NUMBER(19,4) CHECK (TotalRefund >= 0),
    ReturnRefCode VARCHAR2(100),
    Status        NVARCHAR2(50),
    CONSTRAINT fk_return_order FOREIGN KEY (OrderID) REFERENCES "ORDER"(OrderID),
    CONSTRAINT fk_return_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);

-- =============================================
-- 21. RETURNDETAIL TABLE (references OrderReturn, Product, Warehouse)
-- =============================================
CREATE TABLE RETURNDETAIL (
    ReturnID          NUMBER,
    ProductID         NUMBER,
    Quantity          NUMBER CHECK (Quantity > 0),
    QC_Status         NVARCHAR2(50),
    TargetWarehouseID NUMBER,
    ActionTaken       NVARCHAR2(100),
    PRIMARY KEY (ReturnID, ProductID),
    CONSTRAINT fk_rtd_return FOREIGN KEY (ReturnID) REFERENCES ORDERRETURN(ReturnID),
    CONSTRAINT fk_rtd_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
    CONSTRAINT fk_rtd_warehouse FOREIGN KEY (TargetWarehouseID) REFERENCES WAREHOUSE(WareHouseID)
);

-- =============================================
-- 22. DETAILINVENTORY TABLE (references Warehouse, Product)
-- =============================================
CREATE TABLE DETAILINVENTORY (
    WarehouseID     NUMBER,
    ProductID       NUMBER,
    CurrentQuantity NUMBER DEFAULT 0,
    RealStock       NUMBER DEFAULT 0 CHECK (RealStock >= 0),
    AvailableStock  NUMBER DEFAULT 0 CHECK (AvailableStock >= 0),
    MinStock        NUMBER CHECK (MinStock >= 0),
    MaxStock        NUMBER CHECK (MaxStock >= 0),
    IsAlertEnabled  NUMBER(1) DEFAULT 1 CHECK (IsAlertEnabled IN (0,1)),
    StorageLocation NVARCHAR2(100),
    PRIMARY KEY (WarehouseID, ProductID),
    CONSTRAINT fk_di_warehouse FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WareHouseID),
    CONSTRAINT fk_di_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 23. NOTIFICATION TABLE (references Employee, Product)
-- =============================================
CREATE TABLE NOTIFICATION (
    NotificationID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    EmployeeID     NUMBER NOT NULL,
    Title          NVARCHAR2(200) NOT NULL,
    ProductID      NUMBER,
    Message        NVARCHAR2(1000) NOT NULL,
    Type           NUMBER CHECK (Type BETWEEN 0 AND 2),
    Status         NUMBER(1) CHECK (Status BETWEEN 0 AND 1),
    CreatedDate    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_notif_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT fk_notif_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 24. REQUESTFORM TABLE (references Employee)
-- =============================================
CREATE TABLE REQUESTFORM (
    RequestID     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    EmployeeID    NUMBER NOT NULL,
    CreatedDate   DATE DEFAULT SYSDATE,
    Status        NVARCHAR2(50) DEFAULT 'Chờ duyệt',
    ApproverID    NUMBER,
    RejectReason  NVARCHAR2(255),
    CONSTRAINT fk_rf_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT fk_rf_approver FOREIGN KEY (ApproverID) REFERENCES EMPLOYEE(EmployeeID)
);

-- =============================================
-- 25. REQUESTDETAIL TABLE (references RequestForm, Product)
-- =============================================
CREATE TABLE REQUESTDETAIL (
    RequestID NUMBER,
    ProductID NUMBER,
    Quantity  NUMBER CHECK (Quantity > 0),
    PRIMARY KEY (RequestID, ProductID),
    CONSTRAINT fk_rqd_request FOREIGN KEY (RequestID) REFERENCES REQUESTFORM(RequestID),
    CONSTRAINT fk_rqd_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 26. TRANSFERTICKET TABLE (references Employee, Warehouse)
-- =============================================
CREATE TABLE TRANSFERTICKET (
    TransferID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    EmployeeID    NUMBER NOT NULL,
    SourceWHID   NUMBER NOT NULL,
    DestWHID     NUMBER NOT NULL,
    Status        NVARCHAR2(50) DEFAULT 'Chờ xuất kho',
    CreatedDate   DATE DEFAULT SYSDATE,
    CONSTRAINT fk_tt_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT fk_tt_source FOREIGN KEY (SourceWHID) REFERENCES WAREHOUSE(WareHouseID),
    CONSTRAINT fk_tt_dest FOREIGN KEY (DestWHID) REFERENCES WAREHOUSE(WareHouseID)
);

-- =============================================
-- 27. TRANSFERTICKETDETAIL TABLE (references TransferTicket, Product)
-- =============================================
CREATE TABLE TRANSFERTICKETDETAIL (
    TransferID      NUMBER,
    ProductID       NUMBER,
    ExportQuantity  NUMBER,
    ReceiveQuantity NUMBER,
    RequestQuantity NUMBER CHECK (RequestQuantity > 0),
    PRIMARY KEY (TransferID, ProductID),
    CONSTRAINT fk_ttd_ticket FOREIGN KEY (TransferID) REFERENCES TRANSFERTICKET(TransferID),
    CONSTRAINT fk_ttd_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 28. IMPORTRECEIPT TABLE (references Employee, Warehouse, RequestForm)
-- =============================================
CREATE TABLE IMPORTRECEIPT (
    ImportReceiptID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    EmployeeID         NUMBER NOT NULL,
    WarehouseID        NUMBER NOT NULL,
    Status             NVARCHAR2(50) DEFAULT 'Bản nháp',
    CreatedDate        DATE DEFAULT SYSDATE,
    RequestID          NUMBER,
    DiscrepancyReason  NVARCHAR2(255),
    DiscrepancyImageURL NVARCHAR2(255),
    HasDiscrepancy     NUMBER DEFAULT 0 CHECK (HasDiscrepancy IN (0,1)),
    CONSTRAINT fk_ir_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT fk_ir_warehouse FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WareHouseID),
    CONSTRAINT fk_ir_request FOREIGN KEY (RequestID) REFERENCES REQUESTFORM(RequestID)
);

-- =============================================
-- 29. IMPORTRECEIPTDETAIL TABLE (references ImportReceipt, Product)
-- =============================================
CREATE TABLE IMPORTRECEIPTDETAIL (
    ImportReceiptID  NUMBER,
    ProductID        NUMBER,
    ExpectedQuantity NUMBER CHECK (ExpectedQuantity > 0),
    ActualQuantity   NUMBER CHECK (ActualQuantity >= 0),
    PRIMARY KEY (ImportReceiptID, ProductID),
    CONSTRAINT fk_ird_receipt FOREIGN KEY (ImportReceiptID) REFERENCES IMPORTRECEIPT(ImportReceiptID),
    CONSTRAINT fk_ird_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 30. EXPORTRECEIPT TABLE (references Employee)
-- =============================================
CREATE TABLE EXPORTRECEIPT (
    ExportReceiptID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    EmployeeID      NUMBER NOT NULL,
    ExportType      NUMBER(1) NOT NULL CHECK (ExportType IN (1,2,3)),
    Reason          NVARCHAR2(255),
    Status          NVARCHAR2(50) DEFAULT 'Đã hoàn thành',
    CreatedDate     DATE DEFAULT SYSDATE,
    CONSTRAINT fk_exportreceipt_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);

-- =============================================
-- 31. EXPORTRECEIPTDETAIL TABLE (references ExportReceipt, Product)
-- =============================================
CREATE TABLE EXPORTRECEIPTDETAIL (
    ExportReceiptID NUMBER,
    ProductID       NUMBER,
    Quantity        NUMBER CHECK (Quantity > 0),
    PRIMARY KEY (ExportReceiptID, ProductID),
    CONSTRAINT fk_erd_receipt FOREIGN KEY (ExportReceiptID) REFERENCES EXPORTRECEIPT(ExportReceiptID),
    CONSTRAINT fk_erd_product FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 32. COUNTSHEET TABLE
-- =============================================
CREATE TABLE COUNTSHEET (
    CountSheetId NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CreatedDate  DATE DEFAULT SYSDATE,
    Status       NUMBER DEFAULT 0 NOT NULL
);

-- =============================================
-- 33. COUNTSHEETDETAIL TABLE (references CountSheet, Warehouse, Product)
-- =============================================
CREATE TABLE COUNTSHEETDETAIL (
    CountSheetId NUMBER,
    WarehouseID  NUMBER,
    ProductId    NUMBER,
    Quantity     NUMBER NOT NULL,
    Note         NVARCHAR2(50),
    PRIMARY KEY (CountSheetId, WarehouseID, ProductId),
    CONSTRAINT fk_csd_countsheet FOREIGN KEY (CountSheetId) REFERENCES COUNTSHEET(CountSheetId),
    CONSTRAINT fk_csd_warehouse FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSE(WareHouseID),
    CONSTRAINT fk_csd_product FOREIGN KEY (ProductId) REFERENCES PRODUCT(ProductID)
);

-- =============================================
-- 34. DISCOUNT TABLE
-- =============================================
CREATE TABLE DISCOUNT (
    DiscountID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    CustomerTypeID    NUMBER,
    DiscountName      NVARCHAR2(100) NOT NULL,
    Value             NUMBER NOT NULL,
    Detail            VARCHAR2(300) NOT NULL,
    AppliedProductIDs VARCHAR2(4000),
    Status            NUMBER DEFAULT 2,
    ExpiryDate        DATE NOT NULL,
    StartDate         DATE NOT NULL,
    CONSTRAINT fk_discount_customertype FOREIGN KEY (CustomerTypeID) REFERENCES CUSTOMERTYPE(CustomerTypeID),
    CONSTRAINT chk_discount_dates CHECK (ExpiryDate > StartDate)
);

-- =============================================
-- 35. LISTDISCOUNT TABLE (references Order, Discount)
-- =============================================
CREATE TABLE LISTDISCOUNT (
    OrderID      NUMBER,
    DiscountID   NUMBER,
    AppliedValue NUMBER NOT NULL,
    PRIMARY KEY (OrderID, DiscountID),
    CONSTRAINT fk_ld_order FOREIGN KEY (OrderID) REFERENCES "ORDER"(OrderID),
    CONSTRAINT fk_ld_discount FOREIGN KEY (DiscountID) REFERENCES DISCOUNT(DiscountID)
);

-- =============================================
-- 36. FEEDBACK TABLE (references OrderDetail, Customer)
-- =============================================
CREATE TABLE FEEDBACK (
    FeedbackID      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    OrderDetailID   NUMBER,
    CustomerID      NUMBER,
    FeedbackComment VARCHAR2(200) NOT NULL,
    FeedBackDate    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AttachmentURL   VARCHAR2(4000),
    Rating          NUMBER NOT NULL,
    CONSTRAINT fk_feedback_orderdetail FOREIGN KEY (OrderDetailID) REFERENCES ORDERDETAIL(OrderDetailID),
    CONSTRAINT fk_feedback_customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);
